[package]
name = "radicalise"
version = "1.5.1"
edition = "2024"

[dependencies]
anyhow = "1.0"
axum = { version = "0.8", features = ["ws"] }
axum-login = { git = "https://github.com/maxcountryman/axum-login.git", rev = "151c72d7a1b4646830f86b4332e6bd6e34d719a7" }
chrono = "0.4"
cookie = { version = "0.18", features = ["signed"] }
lazy_static = "1.5"
password-auth = "1.0"
reqwest = { version = "0.13", features = ["rustls"] }
resend-rs = "0.32"
serde = "1.0"
serde_json = "1.0"
sqlx = { version = "0.9", features = [
  "runtime-tokio",
  "tls-native-tls",
  "sqlite",
] }
thiserror = "2.0"
time = "0.3"
tokio = { version = "1.45", features = ["macros", "rt-multi-thread"] }
tower = "0.5"
tower-http = { version = "0.7", features = ["cors", "fs"] }
tower-sessions = { version = "0.15", features = ["signed"] }
tower-sessions-sqlx-store = { git = "https://github.com/maxcountryman/tower-sessions-stores.git", rev = "75cb75792d0a8d9231723b07e7524897201ef73b", features = [
  "sqlite",
] }
urlencoding = "2.1"
utoipa = "6.0"
utoipa-axum = "0.3"
utoipa-swagger-ui = { version = "10.0", features = ["axum", "vendored"] }
uuid = { version = "1.17", features = ["v4"] }
openssl = { version = "0.10", features = ["vendored"] }
icalendar = { version = "0.17", default-features = false }
futures-util = "0.3"
rand = "0.10"
